# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pylint pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Error check all code with flake8
      run: |
        # Check the build for python syntax errors or undefined names
        flake8 jupylint/ --count --select=E9,F63,F7,F82 --show-source --statistics
    - name: Lint main source file with pylint
      run: |
        pylint jupylint/jupylint.py
    - name: Run unit tests with pytest
      run: |
        pytest
